services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # bilgisayarımda bulunan /var/lib/docker/volumes içerisinde postgres_data volume'unu container içerisinde postgresql datalarının bulunduğu /var/lib/postgresql/data klasörüne mount ettim.